fix: fix bug where password was not reset after logout
Lokavaluto/monujo pull request #191
Opened 2022-04-13 12:25 UTC by seegwen

Fix bug where password was not reset after logout which caused a password prompt wrongly stating that the password was
entered with an error. The error was on the wallet remembered password and happened upon validating a transaction, ogging out, logging in, and immediately try to perform a money transaction with this second account.

2022-04-14 09:58 UTC, MatSarr approved these changes
Functional review OK

2022-05-16 14:00 UTC, seegwen commented
Needs code review @SeddikKadi @vaab @stephansainleger

2022-06-13 17:08 UTC, vaab requested changes
I have pushed the rebased version on latest `vaab/fix_pwd_in_memory` on my remote.
I also applied:
- code reformatting according to prettier
- removal of the useless encapsulation inside a function that is instantly called.
This can be a simple way for you to verify on your end that everything is good according to your view, and quickly make this PR pass.

2022-06-14 16:18 UTC, seegwen commented on src/services/lokapiService.ts
> +    this.requestLocalPassword = (state => {
I get it, yes. Thanks for the pointer.

2022-06-14 16:18 UTC, seegwen commented on src/services/lokapiService.ts
> +  rememberedPassword:any = { pwd: '', inputTime: 0 }
Allright. Thanks.

2022-06-14 16:19 UTC, seegwen commented on src/services/lokapiService.ts
> +            'Ré-essayez une nouvelle fois'  // XXXvlab: need i18n
That was in the pipe, I know I have to get used to using it.

2022-06-14 16:30 UTC, seegwen commented
@vaab I used your branch, thank you.

Retained the signed-off-by, changed the related issue from #118 to #188.

2022-06-15 18:08 UTC, merged