Fix user disconnected from Monujo when he uses other apps and comes back
Lokavaluto/monujo pull request #262
Opened 2022-07-05 14:21 UTC by seegwen

fixes #252

Will prevent "Monujo account disconnection when switching between
several apps", where the user was not really disconnected, but only
navigated to the login (aka root) page automatically when focusing back
on the Monujo app after using some other app. This code will ensure the
user will access the login page only if he is really disconnected,
otherwise he will be redirected to his dashboard.

2022-07-21 14:29 UTC, SeddikKadi approved these changes
I tested it and couldn't found any unwonted disconnect, the fix looks good

2022-08-08 09:57 UTC, stephansainleger requested changes
Not working for me with the `Back` button, with a **Fairphone 3+** on **/e/OS**
My scenario:
 - run app connected to `dev3.lokavaluto.fr`
 - connected with `vl_part1@0k.io`
 - once on the dashboard, I use the `Back` button to go back to my smartphone home
 - I open several other app
 - With the button `Open apps` I go back on Monujo
 - login screen is displayed, even if I am considered as connected as the main menu propose to go on the dashboard.
 Please note that everything works fine when I use the button `Home` instead of `Back`.

2022-08-26 10:45 UTC, seegwen commented
@stephansainleger The proposed code was valable and triggered in rare cases. I changed it so it is systematic. Can you review it again please ?

2022-09-05 19:52 UTC, stephansainleger approved these changes
Scenario now working, thanks ! :-)

2022-09-06 08:01 UTC, vaab approved these changes

2022-09-06 08:02 UTC, merged