WIP: [NEW] add carto entry for web and mobile app
Lokavaluto/monujo pull request #74
Opened 2022-01-28 11:37 UTC by njeudy

First release of carto implemetation

TODO: a way to have dynamic map url.

2022-01-28 16:00 UTC, seegwen requested changes
There are a lot of indentation fixes. Though I tend to do the same and fix what's under my keyboard, I think what Valentin told me is a good remark though and I try to follow the advice: To try and keep one and only one concern for each PR. 

Betterwise, I think the lint PR #63 will do what you just did, but on the entire codebase.

I don't mind for this PR.

Can you address my comments about the links in the Nav, and then I'll validate and we can merge.

2022-01-28 16:00 UTC, seegwen commented on src/components/Nav.vue
> +          <a class="navbar-link"> Se connecter </a>
There, removing the extra `<a class="navbar-link"`

2022-01-31 14:03 UTC, njeudy commented on src/components/Nav.vue
> +          <a class="navbar-link"> Carto </a>
ok

2022-02-01 08:04 UTC, njeudy commented
@seegwen Ok code updated :)

2022-02-01 09:17 UTC, seegwen approved these changes

2022-02-01 09:17 UTC, merged